import { Resend } from "resend";
import * as fs from "fs";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendReportEmail(
  toEmail: string,
  toName: string,
  companyName: string,
  pdfPath: string
): Promise<void> {
  const pdfBuffer = fs.readFileSync(pdfPath);
  const pdfBase64 = pdfBuffer.toString("base64");
  const fileName = `AI-Readiness-Assessment-${companyName.replace(/\s+/g, "-")}.pdf`;

  const { data, error } = await resend.emails.send({
    from: process.env.FROM_EMAIL || "onboarding@resend.dev",
    to: [toEmail],
    subject: `Your AI Readiness Assessment Report — ${companyName}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #1a1a2e;">
        <div style="background: linear-gradient(135deg, #0A0F2C 0%, #1a237e 100%); padding: 40px; text-align: center; border-radius: 8px 8px 0 0;">
          <h1 style="color: #ffffff; margin: 0; font-size: 24px; letter-spacing: 1px;">AI READINESS ASSESSMENT</h1>
          <p style="color: #90caf9; margin: 8px 0 0 0; font-size: 14px;">Workforce & Business Transformation Report</p>
        </div>
        <div style="background: #f8f9fa; padding: 40px; border: 1px solid #e0e0e0; border-top: none; border-radius: 0 0 8px 8px;">
          <p style="font-size: 16px; color: #333;">Dear ${toName},</p>
          <p style="font-size: 15px; color: #555; line-height: 1.6;">
            Thank you for completing the AI Readiness Assessment for <strong>${companyName}</strong>.
            Please find your personalised report attached to this email.
          </p>
          <p style="font-size: 15px; color: #555; line-height: 1.6;">
            Your report includes:
          </p>
          <ul style="color: #555; line-height: 2; font-size: 14px;">
            <li>Industry Future Outlook with AI</li>
            <li>Disruption Risk Analysis specific to your company</li>
            <li>Risk Management &amp; Job Redesign Roadmap</li>
            <li>AI Disruption Scores for your top 15 roles</li>
            <li>Emerging roles to capitalise on</li>
            <li>Available Singapore grants to fund your journey</li>
            <li>Business &amp; Workforce ROI Projection</li>
            <li>Personalised Next Steps</li>
          </ul>
          <div style="text-align: center; margin: 32px 0;">
            <p style="font-size: 13px; color: #888; margin: 0;">Report generated by</p>
            <p style="font-size: 15px; color: #1a237e; font-weight: bold; margin: 4px 0 0 0;">Workforce Alliance Foundation</p>
          </div>
          <p style="font-size: 13px; color: #aaa; text-align: center; margin-top: 24px;">
            This report was generated using AI and industry data. For a personalised advisory session, contact us at waf.org.sg.
          </p>
        </div>
      </div>
    `,
    attachments: [
      {
        filename: fileName,
        content: pdfBase64,
      },
    ],
  });

  if (error) {
    throw new Error(`Resend error: ${JSON.stringify(error)}`);
  }
  console.log(`Resend email ID: ${data?.id}`);
}
