import Link from "next/link";

const features = [
  {
    icon: "🔭",
    title: "Industry Future Outlook",
    desc: "AI-driven trends reshaping your sector over the next 3–5 years",
  },
  {
    icon: "⚠️",
    title: "Disruption Risk Analysis",
    desc: "Personalised risk matrix — what threatens your business and when",
  },
  {
    icon: "🔄",
    title: "Job Redesign Roadmap",
    desc: "Practical strategies to transform roles, not eliminate them",
  },
  {
    icon: "📊",
    title: "AI Disruption Index",
    desc: "Scores for your top 15 roles — who is most at risk from AI",
  },
  {
    icon: "🌱",
    title: "Emerging Roles",
    desc: "New positions your company should create to stay ahead",
  },
  {
    icon: "💰",
    title: "Singapore Grants",
    desc: "SFEC, EDG, PSG, CCP and more — funding for your journey",
  },
  {
    icon: "📈",
    title: "3-Year ROI Projection",
    desc: "Business and workforce ROI forecast with breakeven analysis",
  },
  {
    icon: "🚀",
    title: "Personalised Next Steps",
    desc: "Phase-by-phase action plan from 30 days to 24 months",
  },
];

export default function LandingPage() {
  return (
    <main className="grid-bg min-h-screen">
      {/* Header */}
      <header className="border-b border-white/5 backdrop-blur-sm sticky top-0 z-50 bg-[#060B1E]/80">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-600 to-violet-600 flex items-center justify-center text-white font-bold text-sm">
              AI
            </div>
            <span className="text-sm font-semibold text-white tracking-wide">
              WAF · AI Assessment
            </span>
          </div>
          <div className="text-xs text-slate-500 hidden sm:block">
            waf.org.sg
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-radial from-blue-900/20 via-transparent to-transparent pointer-events-none" />
        <div className="max-w-6xl mx-auto px-6 pt-20 pb-16 text-center">
          <div className="inline-flex items-center gap-2 bg-blue-950/60 border border-blue-800/40 rounded-full px-4 py-1.5 mb-8">
            <span className="w-2 h-2 rounded-full bg-blue-400 animate-pulse" />
            <span className="text-xs text-blue-300 font-medium tracking-wide uppercase">
              Free AI Readiness Assessment
            </span>
          </div>

          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black text-white leading-tight tracking-tight mb-6">
            Is Your Business
            <span className="block bg-gradient-to-r from-blue-400 to-violet-400 bg-clip-text text-transparent">
              Ready for the AI Era?
            </span>
          </h1>

          <p className="text-lg text-slate-400 max-w-2xl mx-auto mb-10 leading-relaxed">
            Complete a 5-minute assessment and receive a{" "}
            <strong className="text-white">personalised consultant-level PDF report</strong>{" "}
            covering disruption risks, workforce transformation, available grants, and your 3-year ROI — sent directly to your inbox.
          </p>

          <Link
            href="/assessment"
            className="inline-flex items-center gap-2 bg-gradient-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-400 text-white font-semibold px-8 py-4 rounded-xl transition-all duration-200 text-base shadow-lg shadow-blue-900/40"
          >
            Start Your Assessment
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
            </svg>
          </Link>

          <p className="text-xs text-slate-600 mt-4">
            Takes ~5 minutes · PDF delivered instantly · No obligations
          </p>
        </div>
      </section>

      {/* What you get */}
      <section className="max-w-6xl mx-auto px-6 pb-16">
        <div className="text-center mb-10">
          <p className="text-xs font-semibold uppercase tracking-widest text-blue-400 mb-3">
            What Your Report Includes
          </p>
          <h2 className="text-2xl sm:text-3xl font-bold text-white">
            A Complete AI Transformation Playbook
          </h2>
          <p className="text-slate-400 mt-3 text-sm max-w-xl mx-auto">
            Generated by AI using the same frameworks used by top management consulting firms
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {features.map((f) => (
            <div
              key={f.title}
              className="bg-white/[0.03] border border-white/[0.07] rounded-xl p-5 hover:border-blue-800/50 hover:bg-white/[0.05] transition-all duration-200"
            >
              <div className="text-2xl mb-3">{f.icon}</div>
              <div className="font-semibold text-white text-sm mb-1">{f.title}</div>
              <div className="text-slate-400 text-xs leading-relaxed">{f.desc}</div>
            </div>
          ))}
        </div>
      </section>

      {/* CTA band */}
      <section className="border-t border-white/5">
        <div className="max-w-6xl mx-auto px-6 py-12 flex flex-col sm:flex-row items-center justify-between gap-6">
          <div>
            <div className="font-bold text-white text-lg">Ready to see your AI readiness score?</div>
            <div className="text-slate-400 text-sm mt-1">
              Join business owners who are getting ahead of the curve.
            </div>
          </div>
          <Link
            href="/assessment"
            className="flex-shrink-0 inline-flex items-center gap-2 bg-white text-[#060B1E] font-semibold px-6 py-3 rounded-xl hover:bg-blue-50 transition-colors text-sm"
          >
            Begin Assessment →
          </Link>
        </div>
      </section>

      <footer className="border-t border-white/5">
        <div className="max-w-6xl mx-auto px-6 py-6 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="text-xs text-slate-600">
            © {new Date().getFullYear()} Workforce Alliance Foundation · waf.org.sg
          </div>
          <div className="text-xs text-slate-700">
            Report generated using AI — for advisory use only
          </div>
        </div>
      </footer>
    </main>
  );
}
